added build build scripts

diff --git a/build/kentBuild b/build/kentBuild
--- a/build/kentBuild
+++ b/build/kentBuild
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 usage='
-  kentBuild [kentDir] [outRoot]
+  kentBuild [-update] [kentDir] [outRoot]
 
 Build kent/src tree and run tests.  
 
@@ -10,8 +10,11 @@ make an copies the regions of the output log containing the errors to stderr.
 This way, both the error message and the context can be seen without needing
 to read through the entire log. If there are no errors, there is no output.
 
-This requires a checked out tree; cvs is not run.
+This requires a checked out tree, a cvs update can optionally be done 
+after a make clean, so that deleted directories can be removed.
 
+Options:
+   -update - do a cvs update after the make clean.
 Arguments:
    o kentDir - top of kent tree; this should be the "kent" directory,
      NOT kent/src.  Defaults  to ~/kent.
@@ -40,6 +43,16 @@ makeErr() {
 }
 
 # begin here
+doUpdate="no"
+while [[ "$1" == -* ]] ; do
+    case $1 in
+        -update) doUpdate="yes" ;;
+        *) echo "Error: invalid option: $1" >&2
+            exit 1;;
+    esac
+    shift
+done
+
 if [ $# -gt 2 ]  ; then
     echo "Error: wrong number of arguments" >&2
     echo "$usage" >&2
@@ -99,6 +112,14 @@ cd $kentDir
 ((cd src && make -k clean) > clean.log 2>&1) || {
     makeErr "clean" clean.log
 }
+
+if [ $doUpdate = "yes" ] ; then
+    (cvs update -d -P > update.log 2>&1) || {
+        echo "Error: kent/src cvs update failed" >&2
+        echo "full log file is on `hostname`: $kentDir/update.log" >&2
+        exit 2
+    }
+fi
 
 ((cd src && make -k) > compile.log 2>&1) || {
     makeErr "compile" compile.log
