Reformatted log file additions No RM

diff --git a/src/utils/qa/hubSearchUpdate b/src/utils/qa/hubSearchUpdate
--- a/src/utils/qa/hubSearchUpdate
+++ b/src/utils/qa/hubSearchUpdate
@@ -7,5 +7,5 @@ PATH=/cluster/bin/x86_64:$PATH
 date
 cd /hive/groups/browser/hubCrawl
 nohup ./doPublicCrawl &> /dev/null #Send stdout & stderr to /dev/null
-echo $? >> /hive/groups/browser/hubCrawl/hubSearchText.log #Return exit status of prev command, 0 = no issue
-echo "HubSearchText Dev cron-updated on `date`" >> /hive/groups/browser/hubCrawl/hubSearchText.log
+echo "HubSearchText Dev cron-updated on `date`. Exit status: $?" >> /hive/groups/browser/hubCrawl/hubSearchText.log 
+#Return exit status of prev command, 0 = no issue
