work on polishing off ensembl/vega load scripts; not perfect yet

diff --git a/src/hg/makeDb/outside/ensembl/ensemblDownload b/src/hg/makeDb/outside/ensembl/ensemblDownload
--- a/src/hg/makeDb/outside/ensembl/ensemblDownload
+++ b/src/hg/makeDb/outside/ensembl/ensemblDownload
@@ -1,6 +1,14 @@
 #!/bin/bash -e
-##download ensembl or vega mysql tables
-[ $# != 3 ] && echo "usage: ensemblDownload species version output-directory" >&2 && echo "   for example: ensemblDownload homo_sapiens core_43_36e /cluster/store8/ensembl/ensembl_core_43_36e" >&2 && exit 1;
+usage="ensemblDownload - download ensembl or vega mysql tables
+usage:
+    ensemblDownload species version outdir
+for example: ensemblDownload homo_sapiens core_45_36g homo_sapiens_45_36g
+"
+[ $# != 3 ] && {
+    echo "Error: wrong number of args:
+$usage" >&2
+    exit 1
+}
 organism=$1
 version=$2
 outdir=$3
@@ -16,6 +24,8 @@ exceptions="density|ditag|dna|dna_align_feature|oligo|protein_align_feature|repe
 tables=`cat tables.tmp |grep -v -E $exceptions`
 #go get them! (if not already downloaded)
 echo "Starting download to $outdir from $input. "
-for i in $tables; do wget --timestamping --no-verbose $input/${i}.txt.table.gz; done  
+for i in $tables; do 
+    wget --timestamping --no-verbose $input/${i}.txt.table.gz
+done  
 zcat seq_region.txt.table.gz | sed -e 's/GeneScaffold/scaffold/'  > seq_region.txt.table
 gzip -f seq_region.txt.table
diff --git a/src/hg/makeDb/outside/ensembl/hgLoadEnsembl b/src/hg/makeDb/outside/ensembl/hgLoadEnsembl
--- a/src/hg/makeDb/outside/ensembl/hgLoadEnsembl
+++ b/src/hg/makeDb/outside/ensembl/hgLoadEnsembl
@@ -1,52 +1,92 @@
 #!/bin/bash -e
-# hgLoadEnsembl - Download enembl gene predictions from ftp site and create tracks in the browser.
-doDownload=1
+usage="hgLoadEnsembl - Download ENEMBL or VEGA genes from ftp site and create tracks in the browser.
+
+usage:
+    hgLoadEnsembl [options] organism version db
+options:
+      -p - load pseudogene track
+      -l liftfile - lift genePreds using this file (usually for contigs to
+         random chroms)
+      -f filterFile - drop ENSEMBL transcript ids that are in this file.
+         Empty lines and whose starting with # are ignored.
+      -s superfamilyDb - create superfamily tables from specified database (use downloadSuperfamily to create it)
+      -d - drop temporary mysql database after finishing
+
+   for example:
+      hgLoadEnsembl homo_sapiens core_45_36g  hg18
+   If version starts with vega_, the VEGA tables are loaded.
+   All output is in the current directory.
+"
 kg=0
 dropdb=0
 pseudo=0
-nibdir=blank
-liftfile=blank
-superfamily=blank
-count=$#
-while getopts "skpdn:l:f:" theOption; do 
-        case $theOption in
-                s ) echo "Skipping Download step" ; doDownload=0; shift ; let count=$count-1 ; let OPTIND=1;;
-                k ) echo "to be loaded knownToEnsembl" ; kg=1 ; shift ; let count=$count-1; let OPTIND=1;;
-                d ) dropdb=1 ; shift ; let count=$count-1; let OPTIND=1;;
-                p ) pseudo=1 ; shift ; let count=$count-1; let OPTIND=1;;
-                n ) nibdir=$OPTARG  ; shift 2  ; let count=$count-2; let OPTIND=1;;
-                l ) liftfile=$OPTARG  ; shift 2  ; let count=$count-2; let OPTIND=1;;
-                f ) superfamily=$OPTARG  ; shift 2  ; let count=$count-2; let OPTIND=1;;
-                \? ) echo "Unknown option chosen"
-                        exit 1;;
-                * ) echo "You need to supply an option!"
-                        exit 2;;
-        esac
+liftfile=NO
+filterFile=NO
+superfamily=NO
+exportOpts=""
+while getopts "kpdl:f:s" theOption; do 
+    case $theOption in
+        k ) kg=1;;
+        d ) dropdb=1;;
+        p ) pseudo=1
+            exportOpts="${exportOpts} -p" ;;
+        l ) liftfile=$OPTARG
+            exportOpts="${exportOpts} -l $liftfile" ;;
+        f ) filterFile=$OPTARG
+            exportOpts="${exportOpts} -f $filterFile";;
+        s ) superfamily=$OPTARG;;
+        \? ) echo "Invalid option: -$theOption" >&2
+             exit 1;;
+        * ) echo "BUG: option $theOption not handled" >&2
+             exit 1;;
+    esac
 done
-[ $count != 4 ] && echo "usage: hgLoadEnsembl [options] organism version input-directory db " >&2 && \
-     echo "      -n nibdir - nib or twobit files for performing gene checks. [Default: /cluster/data/<db>/<db>.2bit]" >&2 && \
-     echo "      -s skip download from ensembl ftp site" >&2 && \
-     echo "      -p load pseudogene track" >&2 && \
-     echo "      -k load knownToEnsembl from knownGene" >&2 && \
-     echo "      -l liftfile - lift genePreds using this file (usually for contigs to random chroms)" >&2 && \
-     echo "      -f superfamilyDb - create superfamily tables from specified database (use downloadSuperfamily to create it)" >&2 && \
-     echo "      -d drop temporary mysql database after finishing" >&2 && \
-     echo "   for example: hgLoadEnsembl homo_sapiens core_43_36e /cluster/store8/ensembl/ensembl_core_43_36e hg18" >&2 && exit 1;
+shift $(($OPTIND - 1))
+[ $# != 3 ] && {
+    echo "Error: wrong number of args:
+$usage" >&2
+    exit 1
+}
 organism=$1
 version=$2
-workingdir=$3
-db=$4
+db=$3
+
 ensDb=ensembl_${organism}_${version}
-[ $nibdir == "blank" ] && nibdir=/cluster/data/$db/$db.2bit;
-echo organism $organism db $db nibdir $nibdir  lift=$liftfile
-mkdir -p $workingdir
-cd $workingdir
-[ $doDownload == 1 ] && ensemblDownload $organism $version $workingdir;
-ensemblDbImport $organism $version $workingdir 
-[ $liftfile == "blank" ] && exportEnsembl $organism $version $workingdir ;
-[ $liftfile != "blank" ] && exportEnsembl -l $liftfile $organism $version $workingdir ;
-geneCheckAndLoad $db $nibdir ensGene.gp ensGeneChk ensGeneChkDetails
-loadEnsembl $workingdir $db 
-[ $superfamily != "blank" ] && ensemblSuperfamily $db $superfamily;
-[ $kg == 1 ] && hgMapToGene $db ensGene knownGene knownToEnsembl ;
-[ $dropdb == 1 ] && echo "dropping database $ensDb in 5 seconds" && sleep 5 && hgsql mysql -e "drop database if exists $ensDb";
+ensDir=${organism}_${version}
+echo organism $organism db $db lift=$liftfile filter=$filterFile
+mkdir -p $ensDir done
+
+set -x
+[ -f done/download.done ] || {
+    ensemblDownload $organism $version $ensDir
+    touch done/download.done
+}
+[ -f done/import.done ] || {
+    ensemblDbImport $organism $version $ensDir
+    touch done/import.done
+}
+[ -f done/export.done ] || {
+    ensemblExport $exportOpts $organism $version $db
+    touch done/export.done
+}
+[ -f done/load.done ] || {
+    ensemblLoad $organism $version $db
+    touch done/load.done
+}
+[ $superfamily != "NO" -a ! -f done/superfamily.done ] && {
+    ensemblSuperfamily $db $superfamily
+    touch done/superfamily.done
+}
+[ $kg == 1 -a ! -f done/kgmap.done ] && {
+    hgMapToGene $db ensGene knownGene knownToEnsembl
+    touch done/kgmap.done
+}
+[ $dropdb == 1 ] && {
+    echo "dropping database $ensDb in 5 seconds"
+    sleep 5
+    hgsql mysql -e "drop database if exists $ensDb"
+    rm -f done/load.done
+}
+
+echo done
+exit 0
